<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Xmipp: googletest-catch-exceptions-test.CatchCxxExceptionsTest Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="xmipp_logo.png"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Xmipp
   &#160;<span id="projectnumber">v3.23.11-Nereus</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespacegoogletest-catch-exceptions-test.html">googletest-catch-exceptions-test</a></li><li class="navelem"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html">CatchCxxExceptionsTest</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest-members.html">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">googletest-catch-exceptions-test.CatchCxxExceptionsTest Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="dynheader">
Inheritance diagram for googletest-catch-exceptions-test.CatchCxxExceptionsTest:</div>
<div class="dyncontent">
<div class="center"><img src="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest__inherit__graph.png" border="0" usemap="#googletest-catch-exceptions-test_8CatchCxxExceptionsTest_inherit__map" alt="Inheritance graph"/></div>
<map name="googletest-catch-exceptions-test_8CatchCxxExceptionsTest_inherit__map" id="googletest-catch-exceptions-test_8CatchCxxExceptionsTest_inherit__map">
</map>
<center><span class="legend">[<a href="graph_legend.html">legend</a>]</span></center></div>
<div class="dynheader">
Collaboration diagram for googletest-catch-exceptions-test.CatchCxxExceptionsTest:</div>
<div class="dyncontent">
<div class="center"><img src="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest__coll__graph.png" border="0" usemap="#googletest-catch-exceptions-test_8CatchCxxExceptionsTest_coll__map" alt="Collaboration graph"/></div>
<map name="googletest-catch-exceptions-test_8CatchCxxExceptionsTest_coll__map" id="googletest-catch-exceptions-test_8CatchCxxExceptionsTest_coll__map">
</map>
<center><span class="legend">[<a href="graph_legend.html">legend</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a2e45e6a6ecc7d4e1171a48f9c30e1306"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#a2e45e6a6ecc7d4e1171a48f9c30e1306">testCatchesCxxExceptionsInFixtureConstructor</a> (self)</td></tr>
<tr class="separator:a2e45e6a6ecc7d4e1171a48f9c30e1306"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae5ed341fb122b7d03da8ce86043166c3"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#ae5ed341fb122b7d03da8ce86043166c3">testCatchesCxxExceptionsInFixtureDestructor</a> (self)</td></tr>
<tr class="separator:ae5ed341fb122b7d03da8ce86043166c3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad7ceec96581c2cfff6267d26a43e2e7d"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#ad7ceec96581c2cfff6267d26a43e2e7d">testCatchesCxxExceptionsInSetUpTestCase</a> (self)</td></tr>
<tr class="separator:ad7ceec96581c2cfff6267d26a43e2e7d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae3b886e83d78eac40718ff0aeb5ee76b"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#ae3b886e83d78eac40718ff0aeb5ee76b">testCatchesCxxExceptionsInTearDownTestCase</a> (self)</td></tr>
<tr class="separator:ae3b886e83d78eac40718ff0aeb5ee76b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aefd6501c46ece89e1558b708d2b7f932"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#aefd6501c46ece89e1558b708d2b7f932">testCatchesCxxExceptionsInSetUp</a> (self)</td></tr>
<tr class="separator:aefd6501c46ece89e1558b708d2b7f932"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab7130e108d4530a70b604a7710229811"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#ab7130e108d4530a70b604a7710229811">testCatchesCxxExceptionsInTearDown</a> (self)</td></tr>
<tr class="separator:ab7130e108d4530a70b604a7710229811"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a48ada29ca056cd94368189ed0509baa8"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#a48ada29ca056cd94368189ed0509baa8">testCatchesCxxExceptionsInTestBody</a> (self)</td></tr>
<tr class="separator:a48ada29ca056cd94368189ed0509baa8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a01731aaf8269fc952559f5684b395119"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#a01731aaf8269fc952559f5684b395119">testCatchesNonStdCxxExceptions</a> (self)</td></tr>
<tr class="separator:a01731aaf8269fc952559f5684b395119"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab2304b62b833f0729e8909ad8615212c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classgoogletest-catch-exceptions-test_1_1CatchCxxExceptionsTest.html#ab2304b62b833f0729e8909ad8615212c">testUnhandledCxxExceptionsAbortTheProgram</a> (self)</td></tr>
<tr class="separator:ab2304b62b833f0729e8909ad8615212c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><pre class="fragment">Tests C++ exception-catching behavior.

   Tests in this test case verify that:
   * C++ exceptions are caught and logged as C++ (not SEH) exceptions
   * Exception thrown affect the remainder of the test work flow in the
     expected manner.
</pre> 
<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00110">110</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a id="a2e45e6a6ecc7d4e1171a48f9c30e1306"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2e45e6a6ecc7d4e1171a48f9c30e1306">&#9670;&nbsp;</a></span>testCatchesCxxExceptionsInFixtureConstructor()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureConstructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00119">119</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;  <span class="keyword">def </span>testCatchesCxxExceptionsInFixtureConstructor(self):</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;        <span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;        <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;        <span class="stringliteral">&#39;in the test fixture\&#39;s constructor&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;        EX_BINARY_OUTPUT)</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInConstructorTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="ae5ed341fb122b7d03da8ce86043166c3"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae5ed341fb122b7d03da8ce86043166c3">&#9670;&nbsp;</a></span>testCatchesCxxExceptionsInFixtureDestructor()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInFixtureDestructor </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00133">133</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;    <span class="keyword">def </span>testCatchesCxxExceptionsInFixtureDestructor(self):</div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;      self.assertTrue(</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;          <span class="stringliteral">&#39;C++ exception with description &#39;</span></div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;          <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span></div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;          <span class="stringliteral">&#39;in the test fixture\&#39;s destructor&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;          EX_BINARY_OUTPUT)</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;      self.assertTrue(</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;          <span class="stringliteral">&#39;CxxExceptionInDestructorTest::TearDownTestSuite() &#39;</span></div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;          <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="aefd6501c46ece89e1558b708d2b7f932"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aefd6501c46ece89e1558b708d2b7f932">&#9670;&nbsp;</a></span>testCatchesCxxExceptionsInSetUp()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUp </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00171">171</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;  <span class="keyword">def </span>testCatchesCxxExceptionsInSetUp(self):</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;        <span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;        <span class="stringliteral">&#39; thrown in SetUp()&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDownTestSuite() &#39;</span></div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTest destructor &#39;</span></div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDown() &#39;</span></div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;                 <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span></div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;                 <span class="stringliteral">&#39;&quot;CxxExceptionInSetUpTest&quot; (no quotes) &#39;</span></div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;                 <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)</div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="ad7ceec96581c2cfff6267d26a43e2e7d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad7ceec96581c2cfff6267d26a43e2e7d">&#9670;&nbsp;</a></span>testCatchesCxxExceptionsInSetUpTestCase()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInSetUpTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00143">143</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;  <span class="keyword">def </span>testCatchesCxxExceptionsInSetUpTestCase(self):</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;        <span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;        <span class="stringliteral">&#39; thrown in SetUpTestSuite()&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInConstructorTest::TearDownTestSuite() &#39;</span></div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;    self.assertFalse(</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTestSuiteTest constructor &#39;</span></div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;    self.assertFalse(</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTestSuiteTest destructor &#39;</span></div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;    self.assertFalse(</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTestSuiteTest::SetUp() &#39;</span></div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;    self.assertFalse(</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTestSuiteTest::TearDown() &#39;</span></div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;    self.assertFalse(</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInSetUpTestSuiteTest test body &#39;</span></div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="ab7130e108d4530a70b604a7710229811"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab7130e108d4530a70b604a7710229811">&#9670;&nbsp;</a></span>testCatchesCxxExceptionsInTearDown()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDown </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00189">189</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;  <span class="keyword">def </span>testCatchesCxxExceptionsInTearDown(self):</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;        <span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;        <span class="stringliteral">&#39; thrown in TearDown()&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInTearDownTest::TearDownTestSuite() &#39;</span></div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInTearDownTest destructor &#39;</span></div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="ae3b886e83d78eac40718ff0aeb5ee76b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae3b886e83d78eac40718ff0aeb5ee76b">&#9670;&nbsp;</a></span>testCatchesCxxExceptionsInTearDownTestCase()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTearDownTestCase </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00166">166</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;  <span class="keyword">def </span>testCatchesCxxExceptionsInTearDownTestCase(self):</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;        <span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;        <span class="stringliteral">&#39; thrown in TearDownTestSuite()&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="a48ada29ca056cd94368189ed0509baa8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a48ada29ca056cd94368189ed0509baa8">&#9670;&nbsp;</a></span>testCatchesCxxExceptionsInTestBody()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesCxxExceptionsInTestBody </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00200">200</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;  <span class="keyword">def </span>testCatchesCxxExceptionsInTestBody(self):</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;        <span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span></div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;        <span class="stringliteral">&#39; thrown in the test body&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDownTestSuite() &#39;</span></div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInTestBodyTest destructor &#39;</span></div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;        <span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDown() &#39;</span></div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;        <span class="stringliteral">&#39;called as expected.&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT, EX_BINARY_OUTPUT)</div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="a01731aaf8269fc952559f5684b395119"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a01731aaf8269fc952559f5684b395119">&#9670;&nbsp;</a></span>testCatchesNonStdCxxExceptions()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testCatchesNonStdCxxExceptions </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00214">214</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;  <span class="keyword">def </span>testCatchesNonStdCxxExceptions(self):</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;    self.assertTrue(</div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;        <span class="stringliteral">&#39;Unknown C++ exception thrown in the test body&#39;</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;        EX_BINARY_OUTPUT)</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;</div></div><!-- fragment -->
</div>
</div>
<a id="ab2304b62b833f0729e8909ad8615212c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab2304b62b833f0729e8909ad8615212c">&#9670;&nbsp;</a></span>testUnhandledCxxExceptionsAbortTheProgram()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def googletest-catch-exceptions-test.CatchCxxExceptionsTest.testUnhandledCxxExceptionsAbortTheProgram </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="googletest-catch-exceptions-test_8py_source.html#l00219">219</a> of file <a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;  <span class="keyword">def </span>testUnhandledCxxExceptionsAbortTheProgram(self):</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    <span class="comment"># Filters out SEH exception tests on Windows. Unhandled SEH exceptions</span></div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    <span class="comment"># cause tests to show pop-up windows there.</span></div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + <span class="stringliteral">&#39;=-*Seh*&#39;</span></div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    <span class="comment"># By default, Google Test doesn&#39;t catch the exceptions.</span></div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    uncaught_exceptions_ex_binary_output = <a class="code" href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a>(</div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;        [EX_EXE_PATH,</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;         NO_CATCH_EXCEPTIONS_FLAG,</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;         FITLER_OUT_SEH_TESTS_FLAG],</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;        env=environ).output</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;    self.assert_(<span class="stringliteral">&#39;Unhandled C++ exception terminating the program&#39;</span></div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;                 <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;    self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;</div><div class="ttc" id="classgtest__test__utils_1_1Subprocess_html"><div class="ttname"><a href="classgtest__test__utils_1_1Subprocess.html">gtest_test_utils.Subprocess</a></div><div class="ttdef"><b>Definition:</b> <a href="gtest__test__utils_8py_source.html#l00196">gtest_test_utils.py:196</a></div></div>
</div><!-- fragment -->
</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>googletest/googletest/test/<a class="el" href="googletest-catch-exceptions-test_8py_source.html">googletest-catch-exceptions-test.py</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.13
</small></address>
</body>
</html>
